### ISSUE TITLE
Received session description before protocol selection error

### ISSUE THREAD

**Issue by SuperSweatyTejas** [KyokoBot/koe#16]
Getting this in the logs
WARN 27 --- [ntLoopGroup-2-2] m.k.k.gateway.VoiceGatewayV4Connection : Received session description before protocol selection? (connection id = .....)

Audio plays for a few seconds then cuts out

**Comment by alula** [comment]
Could you provide more details?
Where and how are you using Koe? Lavalink, own software?

**Comment by alula** [comment]
Also this seems like Discord's bug - according to documentation you need to send a "select protocol" packet before receiving a session description, but Koe will never do that before receiving READY: https://github.com/KyokoBot/koe/blob/6bd480a258db3687a927a9c0373889574c3ad068/core/src/main/java/moe/kyokobot/koe/gateway/VoiceGatewayV4Connection.java#L77
