### ISSUE TITLE
Broken dependency after February 1st

### ISSUE THREAD

**Issue by freyacodes** [KyokoBot/koe#19]
Koe's `ext-udpqueue` depends on `com.sedmelluq:udp-queue:1.1.0-linux64` from JCenter. JCenter will stop providing artifacts after February 1st.

**Comment by alula** [comment]
Could you make a quick PR that replaces it with another working repo?

**Comment by freyacodes** [comment]
I'm not aware of any repo but maybe jitpack will do the trick

**Comment by duncte123** [comment]
Jcenter will remain readonly: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by alula** [comment]
It would still be good to move in case of need for new build
